language: python
sudo: true

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "3.9-dev"
    - python: "nightly"

services:
  - postgresql

install:
  - pip install -U pip wheel 
  - pip install anyblok psycopg2
  - pip install flake8 coverage pytest pytest-cov
  - pip install colour passlib furl phonenumbers pycountry  # special columns
  - pip install -U cryptography
  - pip install coveralls
  - pip install -e .

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres

script:
  - flake8 anyblok_io --exclude=*/tests/*
  - psql -c 'create database travis_ci_test;' -U postgres
  - pytest --cov-report= --cov=anyblok_io anyblok_io/tests
  - psql -c 'drop database travis_ci_test;' -U postgres
  - anyblok_createdb --install-all-bloks
  - pytest --cov-report= --cov=anyblok_io anyblok_io/bloks
  
after_success:
  coveralls --data_file=.coverage --config_file=.coveragerc
