language: python
sudo: true
addons:
    postgresql: "9.6"

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "3.9-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "3.3"
    - python: "3.6-dev"
    - python: "3.7-dev"
    - python: "nightly"

virtualenv:
  system_site_packages: false

services:
  - postgresql

install:
  - pip install -U pip
  - pip install wheel
  - pip install psycopg2
  - pip install sqlalchemy
  - pip install flake8
  - pip install coverage
  - pip install nose
  - pip install coveralls
  - python setup.py develop

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres

script:
  - flake8 anyblok
  - psql -c 'create database travis_ci_test;' -U postgres
  - nosetests anyblok_io/tests -v -s --with-coverage --cover-package=anyblok_io
  - psql -c 'drop database travis_ci_test;' -U postgres
  - anyblok_createdb --install-all-bloks
  - nosetests anyblok_io/bloks --with-anyblok-bloks -v -s --with-coverage --cover-package=anyblok_io
  
after_success:
  coveralls
